/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KeysIndexRouteImport } from './routes/keys/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EndpointsIndexRouteImport } from './routes/endpoints/index'
import { Route as DlqIndexRouteImport } from './routes/dlq/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EndpointsEndpointIdIndexRouteImport } from './routes/endpoints/$endpointId/index'
import { Route as EndpointsEndpointIdTargetsIndexRouteImport } from './routes/endpoints/$endpointId/targets/index'
import { Route as EndpointsEndpointIdRulesIndexRouteImport } from './routes/endpoints/$endpointId/rules/index'
import { Route as EndpointsEndpointIdTargetsTargetIdEditRouteImport } from './routes/endpoints/$endpointId/targets/$targetId/edit'
import { Route as EndpointsEndpointIdRulesRuleIdEditRouteImport } from './routes/endpoints/$endpointId/rules/$ruleId/edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysIndexRoute = KeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsIndexRoute = EndpointsIndexRouteImport.update({
  id: '/endpoints/',
  path: '/endpoints/',
  getParentRoute: () => rootRouteImport,
} as any)
const DlqIndexRoute = DlqIndexRouteImport.update({
  id: '/dlq/',
  path: '/dlq/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsEndpointIdIndexRoute =
  EndpointsEndpointIdIndexRouteImport.update({
    id: '/endpoints/$endpointId/',
    path: '/endpoints/$endpointId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EndpointsEndpointIdTargetsIndexRoute =
  EndpointsEndpointIdTargetsIndexRouteImport.update({
    id: '/endpoints/$endpointId/targets/',
    path: '/endpoints/$endpointId/targets/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EndpointsEndpointIdRulesIndexRoute =
  EndpointsEndpointIdRulesIndexRouteImport.update({
    id: '/endpoints/$endpointId/rules/',
    path: '/endpoints/$endpointId/rules/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EndpointsEndpointIdTargetsTargetIdEditRoute =
  EndpointsEndpointIdTargetsTargetIdEditRouteImport.update({
    id: '/endpoints/$endpointId/targets/$targetId/edit',
    path: '/endpoints/$endpointId/targets/$targetId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const EndpointsEndpointIdRulesRuleIdEditRoute =
  EndpointsEndpointIdRulesRuleIdEditRouteImport.update({
    id: '/endpoints/$endpointId/rules/$ruleId/edit',
    path: '/endpoints/$endpointId/rules/$ruleId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dlq/': typeof DlqIndexRoute
  '/endpoints/': typeof EndpointsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/endpoints/$endpointId/': typeof EndpointsEndpointIdIndexRoute
  '/endpoints/$endpointId/rules/': typeof EndpointsEndpointIdRulesIndexRoute
  '/endpoints/$endpointId/targets/': typeof EndpointsEndpointIdTargetsIndexRoute
  '/endpoints/$endpointId/rules/$ruleId/edit': typeof EndpointsEndpointIdRulesRuleIdEditRoute
  '/endpoints/$endpointId/targets/$targetId/edit': typeof EndpointsEndpointIdTargetsTargetIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dlq': typeof DlqIndexRoute
  '/endpoints': typeof EndpointsIndexRoute
  '/events': typeof EventsIndexRoute
  '/keys': typeof KeysIndexRoute
  '/endpoints/$endpointId': typeof EndpointsEndpointIdIndexRoute
  '/endpoints/$endpointId/rules': typeof EndpointsEndpointIdRulesIndexRoute
  '/endpoints/$endpointId/targets': typeof EndpointsEndpointIdTargetsIndexRoute
  '/endpoints/$endpointId/rules/$ruleId/edit': typeof EndpointsEndpointIdRulesRuleIdEditRoute
  '/endpoints/$endpointId/targets/$targetId/edit': typeof EndpointsEndpointIdTargetsTargetIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/dlq/': typeof DlqIndexRoute
  '/endpoints/': typeof EndpointsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/keys/': typeof KeysIndexRoute
  '/endpoints/$endpointId/': typeof EndpointsEndpointIdIndexRoute
  '/endpoints/$endpointId/rules/': typeof EndpointsEndpointIdRulesIndexRoute
  '/endpoints/$endpointId/targets/': typeof EndpointsEndpointIdTargetsIndexRoute
  '/endpoints/$endpointId/rules/$ruleId/edit': typeof EndpointsEndpointIdRulesRuleIdEditRoute
  '/endpoints/$endpointId/targets/$targetId/edit': typeof EndpointsEndpointIdTargetsTargetIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/setup'
    | '/events/$eventId'
    | '/dlq/'
    | '/endpoints/'
    | '/events/'
    | '/keys/'
    | '/endpoints/$endpointId/'
    | '/endpoints/$endpointId/rules/'
    | '/endpoints/$endpointId/targets/'
    | '/endpoints/$endpointId/rules/$ruleId/edit'
    | '/endpoints/$endpointId/targets/$targetId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/setup'
    | '/events/$eventId'
    | '/dlq'
    | '/endpoints'
    | '/events'
    | '/keys'
    | '/endpoints/$endpointId'
    | '/endpoints/$endpointId/rules'
    | '/endpoints/$endpointId/targets'
    | '/endpoints/$endpointId/rules/$ruleId/edit'
    | '/endpoints/$endpointId/targets/$targetId/edit'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/login'
    | '/setup'
    | '/events/$eventId'
    | '/dlq/'
    | '/endpoints/'
    | '/events/'
    | '/keys/'
    | '/endpoints/$endpointId/'
    | '/endpoints/$endpointId/rules/'
    | '/endpoints/$endpointId/targets/'
    | '/endpoints/$endpointId/rules/$ruleId/edit'
    | '/endpoints/$endpointId/targets/$targetId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  DlqIndexRoute: typeof DlqIndexRoute
  EndpointsIndexRoute: typeof EndpointsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  KeysIndexRoute: typeof KeysIndexRoute
  EndpointsEndpointIdIndexRoute: typeof EndpointsEndpointIdIndexRoute
  EndpointsEndpointIdRulesIndexRoute: typeof EndpointsEndpointIdRulesIndexRoute
  EndpointsEndpointIdTargetsIndexRoute: typeof EndpointsEndpointIdTargetsIndexRoute
  EndpointsEndpointIdRulesRuleIdEditRoute: typeof EndpointsEndpointIdRulesRuleIdEditRoute
  EndpointsEndpointIdTargetsTargetIdEditRoute: typeof EndpointsEndpointIdTargetsTargetIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys/': {
      id: '/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof KeysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/': {
      id: '/endpoints/'
      path: '/endpoints'
      fullPath: '/endpoints/'
      preLoaderRoute: typeof EndpointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlq/': {
      id: '/dlq/'
      path: '/dlq'
      fullPath: '/dlq/'
      preLoaderRoute: typeof DlqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$endpointId/': {
      id: '/endpoints/$endpointId/'
      path: '/endpoints/$endpointId'
      fullPath: '/endpoints/$endpointId/'
      preLoaderRoute: typeof EndpointsEndpointIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$endpointId/targets/': {
      id: '/endpoints/$endpointId/targets/'
      path: '/endpoints/$endpointId/targets'
      fullPath: '/endpoints/$endpointId/targets/'
      preLoaderRoute: typeof EndpointsEndpointIdTargetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$endpointId/rules/': {
      id: '/endpoints/$endpointId/rules/'
      path: '/endpoints/$endpointId/rules'
      fullPath: '/endpoints/$endpointId/rules/'
      preLoaderRoute: typeof EndpointsEndpointIdRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$endpointId/targets/$targetId/edit': {
      id: '/endpoints/$endpointId/targets/$targetId/edit'
      path: '/endpoints/$endpointId/targets/$targetId/edit'
      fullPath: '/endpoints/$endpointId/targets/$targetId/edit'
      preLoaderRoute: typeof EndpointsEndpointIdTargetsTargetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints/$endpointId/rules/$ruleId/edit': {
      id: '/endpoints/$endpointId/rules/$ruleId/edit'
      path: '/endpoints/$endpointId/rules/$ruleId/edit'
      fullPath: '/endpoints/$endpointId/rules/$ruleId/edit'
      preLoaderRoute: typeof EndpointsEndpointIdRulesRuleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  DlqIndexRoute: DlqIndexRoute,
  EndpointsIndexRoute: EndpointsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  KeysIndexRoute: KeysIndexRoute,
  EndpointsEndpointIdIndexRoute: EndpointsEndpointIdIndexRoute,
  EndpointsEndpointIdRulesIndexRoute: EndpointsEndpointIdRulesIndexRoute,
  EndpointsEndpointIdTargetsIndexRoute: EndpointsEndpointIdTargetsIndexRoute,
  EndpointsEndpointIdRulesRuleIdEditRoute:
    EndpointsEndpointIdRulesRuleIdEditRoute,
  EndpointsEndpointIdTargetsTargetIdEditRoute:
    EndpointsEndpointIdTargetsTargetIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
